[config]
backup_interval = 1

[buckets]
[buckets.bucket]
application_id = ""
application_key = ""
bucket_id = ""

[hosts]
[hosts.server]
db_host = ""
db_port = 3306
db_username = ""
db_password = ""

[databases]
[databases.database]
db_name = ""
db_host = "server"
bucket = "bucket"
remote_path = ""
databases = ""
